# Generated by Django 4.2.1 on 2023-06-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_tags_project_vote_count_project_vote_ration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vote_ration',
            new_name='vote_ratio',
        ),
    ]
