# Generated by Django 4.2.1 on 2023-06-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-created', 'title']},
        ),
    ]
